name: check-format-java-files

on:
  pull_request:
    branches: [ main ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true
      - name: Print diffs
        run: |
          echo "!! TO FIX THIS: TAKE A LOOK AT README FOR INSTALLING PRE_COMMIT HOOK"
          git --no-pager diff --exit-code
