name: deploy-app-and-run-tests-on-merge-to-main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trigger-tests-manually:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      test-environment: 'local'
      tests-to-execute: 'unit'
      tests-to-exclude: 'failing,flaky'
    secrets: inherit
