# This workflow can be run manually by providing inputs

name: deploy-app-and-run-tests-manually

on:
  workflow_dispatch:
    inputs:
      tests-to-execute:
        description: 'Provide tags separated by comma. Possible values : unit,sanity,login,signup'
        required: true
        default: 'unit'
      tests-to-exclude:
        description: 'Provide tags separated by comma. Possible values : flaky,failing'
        required: false
        default: ''
      test-environment:
        description: 'local or development'
        required: false
        default: ''
        type: choice
        options:
          - 'local'
          - 'development'

jobs:
  trigger-tests-manually:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      tests-to-execute: ${{ github.event.inputs.tests-to-execute }}
      tests-to-exclude: ${{ github.event.inputs.tests-to-exclude }}
      test-environment: ${{ github.event.inputs.test-environment }}
    secrets: inherit