name: deploy-app-and-run-tests-on-pr

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  trigger-tests-manually:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      test-environment: ''
      tests-to-execute: 'unit'
      tests-to-exclude: 'failing,flaky'
    secrets: inherit
